Revert "backend: Allow local builds to use the src backend_default_config.json"
* external/libpisp/src/libpisp/backend/backend_default_config.cpp:37:25:
  error: use of undeclared identifier '_DYNAMIC'
          const ElfW(Dyn) *dyn = _DYNAMIC;
                                 ^
This reverts commit 6ca92c34f4f63f7d0df1e419ab659f6a802a5ff1.